name: template-CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  life-cycle-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies.
      run: yarn install

    - name: Test and coverage.
      run: yarn test
